# Generated by Django 4.2.6 on 2023-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
