# Generated by Django 4.2.6 on 2023-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
